// Auto-generated frame asset list for Rabbit Painting School Crest Animation
export const HERO_FRAMES = [
  require('@/assets/hero-frames/frame_001.png'),
  require('@/assets/hero-frames/frame_002.png'),
  require('@/assets/hero-frames/frame_003.png'),
  require('@/assets/hero-frames/frame_004.png'),
  require('@/assets/hero-frames/frame_005.png'),
  require('@/assets/hero-frames/frame_006.png'),
  require('@/assets/hero-frames/frame_007.png'),
  require('@/assets/hero-frames/frame_008.png'),
  require('@/assets/hero-frames/frame_009.png'),
  require('@/assets/hero-frames/frame_010.png'),
  require('@/assets/hero-frames/frame_011.png'),
  require('@/assets/hero-frames/frame_012.png'),
  require('@/assets/hero-frames/frame_013.png'),
  require('@/assets/hero-frames/frame_014.png'),
  require('@/assets/hero-frames/frame_015.png'),
  require('@/assets/hero-frames/frame_016.png'),
  require('@/assets/hero-frames/frame_017.png'),
  require('@/assets/hero-frames/frame_018.png'),
  require('@/assets/hero-frames/frame_019.png'),
  require('@/assets/hero-frames/frame_020.png'),
  require('@/assets/hero-frames/frame_021.png'),
  require('@/assets/hero-frames/frame_022.png'),
  require('@/assets/hero-frames/frame_023.png'),
  require('@/assets/hero-frames/frame_024.png'),
  require('@/assets/hero-frames/frame_025.png'),
  require('@/assets/hero-frames/frame_026.png'),
  require('@/assets/hero-frames/frame_027.png'),
  require('@/assets/hero-frames/frame_028.png'),
  require('@/assets/hero-frames/frame_029.png'),
  require('@/assets/hero-frames/frame_030.png'),
  require('@/assets/hero-frames/frame_031.png'),
  require('@/assets/hero-frames/frame_032.png'),
  require('@/assets/hero-frames/frame_033.png'),
  require('@/assets/hero-frames/frame_034.png'),
  require('@/assets/hero-frames/frame_035.png'),
  require('@/assets/hero-frames/frame_036.png'),
  require('@/assets/hero-frames/frame_037.png'),
  require('@/assets/hero-frames/frame_038.png'),
  require('@/assets/hero-frames/frame_039.png'),
  require('@/assets/hero-frames/frame_040.png'),
];

export const TOTAL_HERO_FRAMES = HERO_FRAMES.length;
